### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by snowinmars** [gusrb3164/react-custom-alert#3]
Hi. There are some issues in the docs:
1. `<ToastContainer floatingTime={5000} />` -> `<AlertContainer floatingTime={5000} />`
2. `import 'react-custom-alert/index.css';` -> `import 'react-custom-alert/dist/index.css';` - otherwise [my webpack](https://github.com/snowinmars/aristotle.paraphrase/blob/master/src/fe/webpack.config.ts) fails to build. The bad news is that in my case css is not applied even from `dist` folder, but I think, I should cast some webpack magic to handle it.

**Comment by gusrb3164** [comment]
Hello @snowinmars.
I released version 0.1.2 by correcting the error. And css seems to work well in create-react-app.
I'll look for more webpack settings related to css.
Thank you :)
